### ISSUE TITLE
First comment about crown

### ISSUE THREAD

**Issue by yiziyu1999** [wph1999/ds4d#1]
Good job, Pinhua! @wph1999 
Have you ever been concerned about the relationship between total height and DBH1?

**Comment by wcy2252110** [comment]
Well done! @wph1999 
And I also agree with you @yiziyu1999, it is a good way to visualize and sense the shape of different trees.

**Comment by GanFanHumankind** [comment]
@wph1999 
I see that you have generated a heat map in the code, which is certainly a workable approach. But I find this heat map a bit too cluttered, would it be clearer to just use a bar chart?

**Comment by LidanXiang2078060** [comment]
Well done! I analyzed the relationship between tree species and the plot. I have seen your analysis of different tree species. Is crown also related to the plot?

**Comment by GanFanHumankind** [comment]
> 
In the August paper I put together, I found no direct correlation between plot and tree cover. Instead, the number cover was derived from crown. I think this may answer the mystery to some extent.

**Comment by YuxuanChen2072510** [comment]
I've concerned at the relationship between DBH and total height. I used scatterplots, and I think they have some relationship. In general, the thicker the tree, the higher the tree. But in the end, there is a relatively flat trend.

**Comment by wph1999** [comment]
> Good job, Pinhua! @wph1999
> Have you ever been concerned about the relationship between total height and DBH1?

Thanks for your comment.
Because I focus on crown, I only consider height and crown, dbh1 and crown. Yuxuanchen answered your question at the bottom. But your question reminds me that maybe we can pick the extremum and see their crown.

**Comment by wph1999** [comment]
> @wph1999
> I see that you have generated a heat map in the code, which is certainly a workable approach. But I find this heat map a bit too cluttered, would it be clearer to just use a bar chart?

Yeah，maybe a bar chart will be more observability. When I plotting the block digram, I just tried to show the relationship as well as their distribution.

**Comment by wph1999** [comment]
> Well done! I analyzed the relationship between tree species and the plot. I have seen your analysis of different tree species. Is crown also related to the plot?

I think there are some relation between plot and crown but it's not easy to see from the data. Maybe we need botanists to help us screen out irrelevant data, and our data are limited, so it is difficult to draw a strong correlation conclusion.

**Comment by wph1999** [comment]
> Well done! @wph1999
> And I also agree with you @yiziyu1999, it is a good way to visualize and sense the shape of different trees.

I agree. DBH, total height and crown are three factors to calculate the biomass of a tree. It can help us better show the state of a tree.
