### ISSUE TITLE
Contour color selection

### ISSUE THREAD

**Issue by LidanXiang2078060** [wph1999/ds4d#3]
Do you think it's better to have red or white contour lines？
![red](https://user-images.githubusercontent.com/95380706/144729032-74a2b8da-297f-4dc9-a72d-84746f7c77fb.jpeg)
![white](https://user-images.githubusercontent.com/95380706/144729039-77a2ddb1-904d-4b16-9077-232549683af6.jpeg)

**Comment by wcy2252110** [comment]
White is better, because the factory may not need to be emphasized.

**Comment by yiziyu1999** [comment]
I think white is better, because there is no red element in the picture

**Comment by yiziyu1999** [comment]
> White is better, because the factory may not need to be emphasized.

Agree with you, and maybe the tree should be emphasized.
