### ISSUE TITLE
Do our presentation slides need add background? Because we need let our audience know where these data from.

### ISSUE THREAD

**Issue by YuxuanChen2072510** [wph1999/ds4d#4]
[data science pre copy.pdf](https://github.com/wph1999/ds4d/files/7656695/data.science.pre.copy.pdf)

**Comment by LidanXiang2078060** [comment]
Yes, I think it is necessary to add the background of the project. In this way, people who are not familiar with our project can more clearly understand the basic information of the project and provide a general project context.

**Comment by LidanXiang2078060** [comment]
Yes, I think it is necessary to add the background of the project. In this way, people who are not familiar with our project can more clearly understand the basic information of the project and provide a general project context.

**Comment by YuxuanChen2072510** [comment]
ok, i'll find related information!
