### ISSUE TITLE
website

### ISSUE THREAD

**Issue by LidanXiang2078060** [wph1999/ds4d#6]
Do you have any suggestions for changing the structure of our website？

**Comment by yiziyu1999** [comment]
Though we do a good job, I think our current shortcoming is that the three parts of the website are not tightly integrated. If the map can be used as a common entrance, it will be more convenient to display the data connection.

**Comment by yiziyu1999** [comment]
Though we do a good job, I think our current shortcoming is that the three parts of the website are not tightly integrated. If the map can be used as a common entrance, it will be more convenient to display the data connection.
