### ISSUE TITLE
The relationship between plot and coverage

### ISSUE THREAD

**Issue by GanFanHumankind** [wph1999/ds4d#7]
I found no direct correlation between plot and tree cover. But it's a bit out of character, anyone have any thoughts on it?

**Comment by wph1999** [comment]
When I checked the relationship between crown and plot, I also thought that the relationship between crown condition and plot was not clear before. I enclose some findings that may be useful to you. I found that in plot10, 13,17,20, more than 60% of the trees had 100% crown cover. They all have the presence of Field ulm trees, especially Plot20, which covers 73% of this specie. If we think of trees in this area as natural selection, then there's a good chance Field ulm is easy to grow.  I got this relationship by drawing the block diagram.
